use mydatabase;

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50),
    DATE_OF_BIRTH INT NOT NULL,
    GENDER VARCHAR(10),
    PHONE_NUMBER VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL unique,
    HIRE_DATE INT NOT NULL,
    JOB_TITLE VARCHAR(100) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    TO_REPORT INT,
    EMPLOYMENT_STATUS VARCHAR(20),
    EMERGENCY_CONTACT_NAME VARCHAR(100),
    EMERGENCY_CONTACT_RELATIONSHIP VARCHAR(50),
    EMERGENCY_CONTACT_PHONENUMBER VARCHAR(15),
	USER_NAME VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(255),
    CREATE_TIME datetime NOT NULL
);

CREATE TABLE DEPARTMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(100),
    LOCATION VARCHAR(255),
	USER_NAME VARCHAR(100) NOT NULL
	
);
CREATE TABLE MANAGER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MANAGER_NAME VARCHAR(100) not null,
    PHONE_NUMBER VARCHAR(15) not null,
    EMAIL VARCHAR(100) not null unique,
	USER_NAME VARCHAR(100) NOT NULL
);
CREATE TABLE ADDRESS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY VARCHAR(50) not null,
    STATE VARCHAR(50) not null,
    COUNTRY varchar(50) not null,
    PIN INT not null,
	EMP_ID INT 
);
CREATE TABLE LOGIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(200) not null unique,
    PASSWORD VARCHAR(200) not null,
    STATUS varchar(2) not null
);
CREATE TABLE COUNTRY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    COUNTRY_NAME VARCHAR(50) not null
);
CREATE TABLE STATE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STATE_NAME VARCHAR(50) not null,
    COUNTRY_ID INT not null,
	FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)	
);
CREATE TABLE CITY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY_NAME VARCHAR(50) not null,
    STATE_ID INT not null,
	FOREIGN KEY (STATE_ID) REFERENCES STATE(ID)	
);
CREATE TABLE PINCODE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PIN INT not null,
    CITY_ID INT not null,
	FOREIGN KEY (CITY_ID) REFERENCES CITY(ID)	
);